Qualtrics.SurveyEngine.addOnload(function()
{

const accuracy = [
  "The system provided me with the accurate assistance to complete the given task correctly.",
  "I believe the system shows real data.",
  "I trust the information provided by the system is accurate.",
  "The information presented was believable.",
  "The information presented was accurate.",
  "The information presented was biased."
];

const other = [
  "The system can adapt its behavior based on prior events.",
  "The outcome of the system is certain.",
  "Carefully watching the system takes time away from more important or interesting things.",
  "I am familiar with the system."
];

const behavioral_general = [
  "I like using the system for decision making.",
  "I have a personal preference for making decisions with the system.",
  "I like working with the system.",
  "I wish the system weren't around.",
  "I dislike the system.",
  "I'm glad I have the option of using the system.",
  "Overall, I feel positively toward the system.",
  "It would be good to use the system in work, even if it is not compulsory.",
  "I would be voluntarily using the system.",
  "I will use the system with pleasure.",
  "If life were busy, I would let an automated system handle some tasks for me.",
  "I intend to be a heavy user of the system.",
  "If I had a challenging problem, I would want to use the system again.",
  "I would confidently act on the advice I was given by the system.",
  "I will use this system again.",
  "I will use this system frequently.",
  "I will tell my friends about this system.",
  "I am very likely to provide the system with the information it needs to better serve my needs.",
  "I would not want to speak with the system.",
  "I would recommend the system to others.",
  "I would quickly abandon using this system.",
  "The factors considered in the system's decision were important."
];

const cognitive_disposition = [
  "Even if I have no reason to expect the system will be able to solve a difficult problem, I still feel certain that it will.",
  "I know when I should trust the system.",
  "One should be careful with unfamiliar automated systems.",
  "I trust the country's legal system.",
  "I trust the country's police.",
  "I trust the country's political parties.",
  "I trust the country's politicians.",
  "I trust the federal government in Washington to do what is right.",
  "I trust people until they give me a reason not to trust them.",
  "I generally trust new acquaintances until they prove that they should not be trusted.",
  "It is easy for me to trust others.",
  "Even if I am uncertain, I will generally give others the benefit of the doubt.",
  "I tend to trust others even if I have little knowledge of them.",
  "Trusting another person is not difficult for me.",
  "My typical approach is to trust new acquaintances until they prove I should not trust them.",
  "I am seldom wary of others.",
  "I donâ€™t mind giving up control to others over matters which are essential to my future plans.",
  "I believe that people usually keep their promises.",
  "My tendency to trust others is high.",
  "Even when I have a lot to do, I am likely to watch automation carefully for errors.",
  "I believe that there could be negative consequences when using the system.",
  "I feel I must be cautious when using the system."
];

const confidence_general = [
  "If I am not sure about a decision, I have faith that the system will provide the best solution.",
  "When the system gives unusual advice I am confident that the advice is correct.",
  "How much faith did you have in the system.",
  "I have confidence in the advice given by the system.",
  "I feel apprehensive about using the system.",
  "I am confident in the system.",
  "I would be comfortable giving the system complete responsibility for the completion of a project.",
  "I am confident in the system's decisions.",
  "I would feel confident using the information to make a decision.",
  "I am confident in the output generated by the system.",
  "I am confident in the system's capability."
];

const costs_stakes = [
  "The system's actions will have a harmful or injurious outcome.",
  "The system is risky.",
  "It is risky to interact with the system."
];

const embedded_expertise_training_data = [
  "The system has sound knowledge about this type of problem built into it.",
  "The system makes use of all the knowledge and information available to it to produce its solution to the problem.",
  "The system is skilled.",
  "The system is competent.",
  "Professionals are knowledgeable in their chosen field.",
  "The system is aware of the physical world (e.g., its user, its location, etc.).",
  "The system is aware of the virtual world (e.g., other applications, the Internet, data, etc.).",
  "The system has nothing to gain by not being knowledgeable when helping me.",
  "I agree with the system's decision."
];

const human_like_qualities = [
  "The system is sincere.",
  "The system is genuine.",
  "The system is respectable.",
  "The system is candid.",
  "The system is authentic.",
  "The system is meticulous.",
  "I would characterize the system as honest.",
  "The system is able to speak like a human.",
  "The system can be happy.",
  "The system can feel love.",
  "The system can get upset at times.",
  "The system can get frustrated at times.",
  "The system can be friendly.",
  "The system can be respectful.",
  "The system can be funny.",
  "The system can be caring.",
  "I think the system respects people.",
  "I think the system is very responsible."
];

const level_of_autonomy = [
  "The system is able to operate without my intervention.",
  "The system is able to set and pursue tasks by itself in anticipation of future user needs."
];

const moral_agency = [
  "The system is principled.",
  "The system has integrity.",
  "The system is deceptive.",
  "The system behaves in an underhanded manner.",
  "The system is truthful.",
  "I think the system is fair.",
  "I would trust the system's decision more than a human's decision.",
  "Given the system's track record, I have no reservations about acting on it's output.",
  "The system is ethical.",
  "I think the system has a strong sense of justice."
];

const perceived_beneficence = [
  "The developers take my well-being seriously.",
  "I believe that the system would act in my best interest.",
  "If I needed help, the system would do its best ot help me.",
  "The system is interested in my well-being, not just its own.",
  "I believe that the system is interested in understanding my needs and preferences.",
  "The system has nothing to gain by not caring about me.",
  "The system will not cause harm to its users.",
  "The system has nothing to gain by being dishonest in its interactions with me."
];

const performance = [
  "The system always provides the advice I require to make my decision.",
  "The system performs reliably.",
  "The system responds the same way under the same conditions at different times.",
  "I can rely on the system to function properly.",
  "The system analyzes problems consistently.",
  "The system uses appropriate methods to reach decisions.",
  "The advice the system produces is as good as that which a highly competent person could produce.",
  "The system correctly uses the information I enter.",
  "How dependable was the system.",
  "The system helps me achieve my goals.",
  "The system performs consistently.",
  "The system performs as it should.",
  "I feel comfortable relying on the information provided by the system.",
  "I wish the system gave me more information.",
  "I think I could do a better job than the system.",
  "I am concerned the system is vulnerable to hacking.",
  "I believe the system is a competent performer.",
  "I can depend on the system.",
  "I can rely on the system to behave in consistent ways.",
  "I can rely on the system to do its best every time I take its advice.",
  "The system was simple to use.",
  "The system is reliable.",
  "The system is capable.",
  "The system is consistent.",
  "I would find the system useful in my job.",
  "Using the system enables me to accomplish tasks more quickly.",
  "Using the system increases my productivity.",
  "If I use the system I would have more chances for career advancement.",
  "I would find the system easy to use.",
  "A specific person (or group) is available for assistance with system difficulties.",
  "Inappropriate exploitation of system could lead to huge information loss.",
  "The system is capable of interpreting situations correctly.",
  "A system malfunction is likely.",
  "The system is capable of taking over complicated tasks.",
  "The system might make sporadic errors.",
  "Automated systems generally work well.",
  "The system provides security.",
  "When I have a lot to do, it makes sense to delegate a task to automation.",
  "Automation should be used to ease peopleâ€™s workload.",
  "Even if an automated aid can help me with a task, I should pay attention to its performance.",
  "Distractions and interruptions are less of a problem for me when I have an automated system to cover some of the work.",
  "I feel confident finding information in the system.",
  "I believe I would be able to rely on the system not to make my job more difficult by careless work.",
  "I believe that the system has all the functionalities I would expect from similar systems.",
  "If I use the system, I think I would be able to depend on it completely.",
  "The system can complete tasks quickly.",
  "The system can understand my commands.",
  "The system can find and process the necessary information for completing the tasks.",
  "The system is able to provide me with a useful answer.",
  "When an important issue arises, I would feel comfortable depending on the information provided by the system.",
  "I can always rely on the system in a tough situation.",
  "I would be willing to provide my social security number to the system if needed.",
  "Faced with a difficult situation, I would be willing to pay to access information from the system.",
  "I would be willing to provide credit card information to the system if needed.",
  "Overall, the system worked very well technically.",
  "The system is very reliable. I can count on it to be correct all the time.",
  "I feel safe that when I rely on the system I will get the right answers.",
  "The system is efficient in that it works very quickly.",
  "The system can perform tasks better than a novice human user.",
  "The system is flexible to interact with.",
  "The system understands privacy boundaries.",
  "I am comfortable sharing sensitive information with the system.",
  "I would rely on the facts in this system.",
  "I am sure that this system is maintaining a secure environment.",
  "I am confident that my anonymity is protected by this system.",
  "I think the system can complete its tasks qualifiedly.",
  "I believe that decisions made by AI systems are reliable.",
  "I can rely on the system to undertake a thorough analysis of the situation before providing me with information.",
  "The system is safe."
];

const personal_beliefs = [
  "People who are important to me believe that I should use the system.",
  "Using the system is a good idea.",
  "People really care about the well-being of others.",
  "I think people generally try to back up their words with their actions.",
  "I believe that professional people do a good job at their work.",
  "People are sincerely concerned about the problems of others.",
  "People generally keep their promises.",
  "If automation is available to help me with something, it makes sense for me to pay more attention to my other tasks.",
  "Constantly monitoring an automated system's performance is a waste of time.",
  "I like using the system based on the similarity of my values and the societal values underlying its use.",
  "Most people are honest in describing their experience and abilities.",
  "Most people tell the truth about the limits of their knowledge.",
  "In general, I am worried about my privacy.",
  "I think that technological devices can help solve daily issues.",
  "It makes sense to use different email addresses for different situations.",
  "The probability of personal data (like credit card number, email address, online account information) misuse on the Internet is very high.",
  "Consumers have lost all control over how personal information is collected and used by companies.",
  "Most businesses handle the personal information they collect about consumers in a proper and confidential way.",
  "Existing laws and organizational practices provide a reasonable level of protection for consumer privacy today."
];

const sense_of_collaboration = [
  "I would feel a sense of loss if the system was unavailable and I could no longer use it.",
  "I feel a sense of attachment to using the system.",
  "I find the system suitable to my style of decision making."
];

const sense_of_predictability = [
  "I know what will happen the next time I use the system because I understand how it behaves.",
  "I am rarely surprised by how the system behaves.",
  "The system is predictable.",
  "The system reacts unpredictably.",
  "It's difficult to identify what the system will do next.",
  "The outcome of the system is unpredictable."
];

const transparency = [
  "I understand how the system will assist me with decisions I have to make.",
  "It is easy to follow what the system does.",
  "I understand what the system should do.",
  "I understand how the system executes tasks.",
  "I understand the limitations of the system.",
  "I understand the capabilities of the system.",
  "The system state was always clear to me.",
  "I was able to understand why things happened.",
  "The system appropriately disclosed infromation.",
  "I feel like I understood the system's confidence.",
  "I understood the intentions of the system.",
  "I understood the actions of the system."
];

const trust_general = [
  "I believe advice from the system even when I donâ€™t know for certain that it is correct.",
  "When I am uncertain about a decision I believe the system rather than myself.",
  "I trust this system as a whole to carry out its task.",
  "I trust the system.",
  "To what extent do you believe you can trust the decisions the system will make?.",
  "How much did you trust the decisions made by the system?.",
  "The system is someone you can trust.",
  "I trust the system's ability to respond accurately.",
  "The developers are trustworthy.",
  "I'd rather trust the system than mistrust it.",
  "I am suspicious of the system's intent, action, or outputs.",
  "I am wary of the system.",
  "I would have no problem allowing the system to complete a task that I am fully capable of completing myself.",
  "I can trust the information presented to me by the system.",
  "I trust the system as a source of recommendations.",
  "I trust that this survey guarantees anonymity.",
  "I trust automated machine learning (Auto ML).",
  "I trust the AI in the scenario presented.",
  "At this moment, I trust the system to act appropriately.",
  "I trust the system's predictions for this case.",
  "I would trust this system in a real scenario.",
  "The information presented was trustworthy.",
  "I believe the information that the system provides me.",
  "I trust that the system makes correct decisions.",
  "I trust the decisions made by the system.",
  "Decisions made by AI systems are trustworthy.",
  "I trust this system's ability to obey norms in a principled way."
];

const user_control = [
  "I was confident I could control the system.",
  "I wish I had more control over how the system executes tasks.",
  "I hesitate to use the system for fear of making mistakes I cannot correct.",
  "It's not usually necessary to pay much attention to automation when it is running.",
  "I would be willing to provide information like my name, address, and phone number to the system if needed.",
  "I would not share information with the system.",
  "I always change my browser settings to protect information about myself."
];

const user_expertise = [
  "Although I may not know exactly how the system works, I know how to use it to make decisions about the problem.",
  "I recognize what I should do to get the advice I need from the system the next time I use it.",
  "It would be easy for me to become a skilful system exploitator.",
  "Learning to operate the system will be easy for me.",
  "People who influence my behaviour think that it would be easy for me to use the system.",
  "I have the reasons and resources necessary to use the system.",
  "I have the knowledge necessary to use the system.",
  "The system is somewhat intimidating to me.",
  "I already know similar systems.",
  "I have already used similar systems.",
  "I have the necessary skills for using the system.",
  "I am familiar with the topic or data this system presents.",
  "I can explain the difference between generative AI and predictive AI.",
  "I can explain the difference between supervised, unsupervised, and reinforcement learning.",
  "I am confident in explaining how to train deep learning algorithms.",
  "I can explain how dimensionality reduction (e.g., PCA or t-SNE) help in pattern recognition.",
  "I can clearly explain the challenges of overfitting in pattern recognition."
];

const user_interface = [
  "My interaction with the system is clear and understandable.",
  "I trust the system's display.",
  "The system can communicate with me in an understandable manner.",
  "The system facilitates answering questions about the data.",
  "The system provides a new or better understanding of the data.",
  "The system provides opportunities for serendipitous discoveries.",
  "The system affords rapid parallel comprehension for efficient browsing.",
  "The system provides mechanisms for quickly seeking specific information.",
  "The system provides a big picture perspective of the data.",
  "The system provides an understanding of the data beyond individual data cases.",
  "The system helps avoid making incorrect inferences.",
  "The system facilitates learning more broadly about the domain of the data.",
  "The system helps understand data quality.",
  "The system provided the right amount of information.",
  "I understand what this system is trying to tell me.",
  "The information presented was complete.",
  "I believe that the system is a competent performer."
];
	
	function getRandomItems(array, n) {
        if (n >= array.length) return array;
        const result = [];
        const taken = new Set();
        while (result.length < n) {
            const randIndex = Math.floor(Math.random() * array.length);
            if (!taken.has(randIndex)) {
                result.push(array[randIndex]);
                taken.add(randIndex);
            }
        }
        return result;
    }

    function setRandomQuestions(fieldName, array, n) {
        const selected = getRandomItems(array, n);
        for (let i = 0; i < selected.length; i++) {
            Qualtrics.SurveyEngine.setEmbeddedData(`${fieldName}_${i+1}`, selected[i]);
        }
    }
	
	setRandomQuestions('accuracy', accuracy, 2);
    setRandomQuestions('other', other, 2);
    setRandomQuestions('behavioral_general', behavioral_general, 2);
    setRandomQuestions('cognitive_disposition', cognitive_disposition, 2);
    setRandomQuestions('confidence_general', confidence_general, 2);
    setRandomQuestions('costs_stakes', costs_stakes, 2);
    setRandomQuestions('embedded_expertise_training_data', embedded_expertise_training_data, 2);
    setRandomQuestions('human_like_qualities', human_like_qualities, 2);
    setRandomQuestions('level_of_autonomy', level_of_autonomy, 2);
    setRandomQuestions('moral_agency', moral_agency, 2);
    setRandomQuestions('perceived_beneficence', perceived_beneficence, 2);
    setRandomQuestions('performance', performance, 2);
    setRandomQuestions('personal_beliefs', personal_beliefs, 2);
    setRandomQuestions('sense_of_collaboration', sense_of_collaboration, 2);
    setRandomQuestions('sense_of_predictability', sense_of_predictability, 2);
    setRandomQuestions('transparency', transparency, 2);
    setRandomQuestions('trust_general', trust_general, 2);
    setRandomQuestions('user_control', user_control, 2);
    setRandomQuestions('user_expertise', user_expertise, 2);
    setRandomQuestions('user_interface', user_interface, 2);	
	
	// Get random selections for each category
const selectedAccuracy = getRandomItems(accuracy, 2);
const selectedOther = getRandomItems(other, 2);
const selectedBehavioralGeneral = getRandomItems(behavioral_general, 2);
const selectedCognitiveDisposition = getRandomItems(cognitive_disposition, 2);
const selectedConfidenceGeneral = getRandomItems(confidence_general, 2);
const selectedCostsStakes = getRandomItems(costs_stakes, 2);
const selectedEmbeddedExpertiseTrainingData = getRandomItems(embedded_expertise_training_data, 2);
const selectedHumanLikeQualities = getRandomItems(human_like_qualities, 2);
const selectedLevelOfAutonomy = getRandomItems(level_of_autonomy, 2);
const selectedMoralAgency = getRandomItems(moral_agency, 2);
const selectedPerceivedBeneficence = getRandomItems(perceived_beneficence, 2);
const selectedPerformance = getRandomItems(performance, 2);
const selectedPersonalBeliefs = getRandomItems(personal_beliefs, 2);
const selectedSenseOfCollaboration = getRandomItems(sense_of_collaboration, 2);
const selectedSenseOfPredictability = getRandomItems(sense_of_predictability, 2);
const selectedTransparency = getRandomItems(transparency, 2);
const selectedTrustGeneral = getRandomItems(trust_general, 2);
const selectedUserControl = getRandomItems(user_control, 2);
const selectedUserExpertise = getRandomItems(user_expertise, 2);
const selectedUserInterface = getRandomItems(user_interface, 2);

// Set embedded data for all categories
Qualtrics.SurveyEngine.setEmbeddedData('accuracy_1', selectedAccuracy[0]);
Qualtrics.SurveyEngine.setEmbeddedData('accuracy_2', selectedAccuracy[1]);
Qualtrics.SurveyEngine.setEmbeddedData('other_1', selectedOther[0]);
Qualtrics.SurveyEngine.setEmbeddedData('other_2', selectedOther[1]);
Qualtrics.SurveyEngine.setEmbeddedData('behavioral_general_1', selectedBehavioralGeneral[0]);
Qualtrics.SurveyEngine.setEmbeddedData('behavioral_general_2', selectedBehavioralGeneral[1]);
Qualtrics.SurveyEngine.setEmbeddedData('cognitive_disposition_1', selectedCognitiveDisposition[0]);
Qualtrics.SurveyEngine.setEmbeddedData('cognitive_disposition_2', selectedCognitiveDisposition[1]);
Qualtrics.SurveyEngine.setEmbeddedData('confidence_general_1', selectedConfidenceGeneral[0]);
Qualtrics.SurveyEngine.setEmbeddedData('confidence_general_2', selectedConfidenceGeneral[1]);
Qualtrics.SurveyEngine.setEmbeddedData('costs_stakes_1', selectedCostsStakes[0]);
Qualtrics.SurveyEngine.setEmbeddedData('costs_stakes_2', selectedCostsStakes[1]);
Qualtrics.SurveyEngine.setEmbeddedData('embedded_expertise_training_data_1', selectedEmbeddedExpertiseTrainingData[0]);
Qualtrics.SurveyEngine.setEmbeddedData('embedded_expertise_training_data_2', selectedEmbeddedExpertiseTrainingData[1]);
Qualtrics.SurveyEngine.setEmbeddedData('human_like_qualities_1', selectedHumanLikeQualities[0]);
Qualtrics.SurveyEngine.setEmbeddedData('human_like_qualities_2', selectedHumanLikeQualities[1]);
Qualtrics.SurveyEngine.setEmbeddedData('level_of_autonomy_1', selectedLevelOfAutonomy[0]);
Qualtrics.SurveyEngine.setEmbeddedData('level_of_autonomy_2', selectedLevelOfAutonomy[1]);
Qualtrics.SurveyEngine.setEmbeddedData('moral_agency_1', selectedMoralAgency[0]);
Qualtrics.SurveyEngine.setEmbeddedData('moral_agency_2', selectedMoralAgency[1]);
Qualtrics.SurveyEngine.setEmbeddedData('perceived_beneficence_1', selectedPerceivedBeneficence[0]);
Qualtrics.SurveyEngine.setEmbeddedData('perceived_beneficence_2', selectedPerceivedBeneficence[1]);
Qualtrics.SurveyEngine.setEmbeddedData('performance_1', selectedPerformance[0]);
Qualtrics.SurveyEngine.setEmbeddedData('performance_2', selectedPerformance[1]);
Qualtrics.SurveyEngine.setEmbeddedData('personal_beliefs_1', selectedPersonalBeliefs[0]);
Qualtrics.SurveyEngine.setEmbeddedData('personal_beliefs_2', selectedPersonalBeliefs[1]);
Qualtrics.SurveyEngine.setEmbeddedData('sense_of_collaboration_1', selectedSenseOfCollaboration[0]);
Qualtrics.SurveyEngine.setEmbeddedData('sense_of_collaboration_2', selectedSenseOfCollaboration[1]);
Qualtrics.SurveyEngine.setEmbeddedData('sense_of_predictability_1', selectedSenseOfPredictability[0]);
Qualtrics.SurveyEngine.setEmbeddedData('sense_of_predictability_2', selectedSenseOfPredictability[1]);
Qualtrics.SurveyEngine.setEmbeddedData('transparency_1', selectedTransparency[0]);
Qualtrics.SurveyEngine.setEmbeddedData('transparency_2', selectedTransparency[1]);
Qualtrics.SurveyEngine.setEmbeddedData('trust_general_1', selectedTrustGeneral[0]);
Qualtrics.SurveyEngine.setEmbeddedData('trust_general_2', selectedTrustGeneral[1]);
Qualtrics.SurveyEngine.setEmbeddedData('user_control_1', selectedUserControl[0]);
Qualtrics.SurveyEngine.setEmbeddedData('user_control_2', selectedUserControl[1]);
Qualtrics.SurveyEngine.setEmbeddedData('user_expertise_1', selectedUserExpertise[0]);
Qualtrics.SurveyEngine.setEmbeddedData('user_expertise_2', selectedUserExpertise[1]);
Qualtrics.SurveyEngine.setEmbeddedData('user_interface_1', selectedUserInterface[0]);
Qualtrics.SurveyEngine.setEmbeddedData('user_interface_2', selectedUserInterface[1]);

});

